# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world - always!
  condition: always()

- script: echo Hello, world - on success!
  condition: succeeded()

- script: echo Hello, world - on failure!
  condition: failed()
